version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Example connection string to PostgreSQL from FastAPI
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydb
    depends_on:
      - postgres

volumes:
  pgdata:
